#!/usr/bin/env python
import subprocess

cmd='srvctl status service -d revppb -s revpptsrv'

p=subprocess.Popen([cmd],shell=True,stdout=subprocess.PIPE, stderr=subprocess.PIPE)

out, err = p.communicate()
print out, err

if "is running" in out:
    print "service running on PPB"
else:
    print "service running on PPA"


-----------------------------------------------------------------------------------------------------------------------------
